### ISSUE TITLE
internationalization of "Lost" and "Travelling" locations

### ISSUE THREAD

**Issue by oncleben31** [malcolmrigg/WizardClock#1]
For those who want to display the clock in their native language, is it possible to implement a translation file or make it customisable in the card settings ?

**Comment by malcolmrigg** [comment]
Done 👍  

Added "lost" and "travelling" options in the config - just set them to whatever text you want and that's what'll be used. I've added an example to the readme file too.

**Comment by oncleben31** [comment]
Great. And thank you.
