### ISSUE TITLE
Customer Background

### ISSUE THREAD

**Issue by schettada** [malcolmrigg/WizardClock#10]
Hi,

How can i get the background color as the one shown in your example picture? for me it comes up as the theme color. 

./Sooraj

**Comment by malcolmrigg** [comment]
Hi, that was the default colour I used before switching to using the theme colours. There's no config override at the moment to use a different colour, but you can change the code in the drawFace() function - look for the line where it sets the fill colour and change it to this:

`      ctx.fillStyle = '#f2e6d9';`

**Comment by schettada** [comment]
Thank you.

On Sep 26, 2020, at 02:35, Malcolm Rigg <notifications@github.com> wrote:

﻿

Hi, that was the default colour I used before switching to using the theme colours. There's no config override at the moment to use a different colour, but you can change the code in the drawFace() function - look for the line where it sets the fill colour and change it to this:

ctx.fillStyle = '#f2e6d9';
