### ISSUE TITLE
Person Entity - handle "unknown"

### ISSUE THREAD

**Issue by auBusinessDaD** [malcolmrigg/WizardClock#13]
Although I could use the device tracker, I am actually looking to use the person entity (which is updated by device tracker and other functions) as this would handle my children (who don't presently have phones).

This works brilliantly out of the box, BUT the config doesn't have any accoomdation for "unknown" status because I believe this was built for a different tracking system (which uses the term "lost").

-- NOTE -- I don't expect this to be fixed by anyone else. I am more adding it as a note that when I get time I will fix this which I will push back to the repo to be considered for a merger with the master ;)

**Comment by realcanadrian** [comment]
Any chance we could get “unknown” bundled into “lost”?

**Comment by malcolmrigg** [comment]
I've added this - "unknown" now gets handled in the same way as the not home state.
