### ISSUE TITLE
Rounded text

### ISSUE THREAD

**Issue by CultusMechanicus** [malcolmrigg/WizardClock#3]
Not really an issue, but rather than the Bezier curve version of text, you might be interested in
[This](http://blog.graphicsgen.com/2015/03/html5-canvas-rounded-text.html) 

Looks like a quick and simplish way of drawing text on a canvas in a circle, with start angles and positioning etc.

**Comment by malcolmrigg** [comment]
Oh, that's cool. Much simpler than the other solutions that I've looked at, thanks! Might have a shot at integrating that soon.

**Comment by malcolmrigg** [comment]
I was struggling to use the function as-is with my code, but managed to extract the useful bits and integrated it into the drawing code, curved text is working :)
