### ISSUE TITLE
Full screen mode?

### ISSUE THREAD

**Issue by mikeage** [malcolmrigg/WizardClock#7]
Hi,

I just added this to my lovelace config, and I love it. I'd like to have a tab that's just this clock; I know I can use "panel mode" to render this full width, but the height is still the default card size, so I just get a left justified regular size clock. Is there any way to control the vertical height, either explicitly or via auto sizing?

**Comment by malcolmrigg** [comment]
Hi, glad you like it. I’ve actually tried to do that before but without much success - I couldn’t figure out a reliable way to get the clock to fill the available vertical space, and I’m no HTML/CSS expert unfortunately 😞 

You should be able to set the size explicitly in the code - look for the two lines setting the height/width to 500px. I have had problems setting this any larger than 500px in the past - haven’t tried it for a while though and I’m not sure whether it was a lovelace issue or a problem with my code, so give it a try and let me know how you get on.

**Comment by mikeage** [comment]
Thanks, I'll keep you posted! (probably won't be until tomorrow)

**Comment by mikeage** [comment]
So just to be clear, this is the first time I've touched CSS since, oh, 2010 or so, and my first time ever looking at HTML5. Also my first time doing anything with lovelace.

That said, I made these two changes which helped a bit:
```diff
--- a/www/community/custom-lovelace/weasley-card.js
+++ b/www/community/custom-lovelace/weasley-card.js
@@ -65,15 +65,18 @@ class WeasleyClockCard extends HTMLElement {
       }
       document.body.appendChild(fontstyle);

+      this.div = document.createElement('div');
+      this.div.style.textAlign = 'center'
       this.canvas = document.createElement('canvas');
-      card.appendChild(this.canvas);
+      this.div.appendChild(this.canvas)
+      card.appendChild(this.div);
       this.appendChild(card);
       this.ctx = this.canvas.getContext("2d");
     }

     this.canvas.style.maxWidth = "-webkit-fill-available";
-    this.canvas.width="500";
-    this.canvas.height="500";
+    this.canvas.width=this.config.width ? this.config.width : "500";
+    this.canvas.height=this.config.width ? this.config.width : "500";

     this.radius = this.canvas.height / 2;
     this.ctx.translate(this.radius, this.radius);
```

The first centers the clock; useful in panel mode. It doesn't seem to have any negative effects on the regular card. The second makes it much easier to set a width/height from the config, rather than reloading the .js each time. 

I found that setting it to 700 pixels worked nicely; it looked good in panel mode on my screen, and it didn't look bad downscaling to the default card size.

But I didn't actually get anywhere with autosizing. It seems like it can be done setting CSS, but I didn't feel like diving too deep in that rabbit hole ;-) I'm probably not going to go any further, other than to say that other sizes did work for me, in case you want to look at it again.

**Comment by malcolmrigg** [comment]
I've (finally) added your suggested code to my version. This works pretty well, and I've used it along with [Wallpanel](https://github.com/j-a-n/lovelace-wallpanel) to create a really nice digital photo frame with the weasley clock in the corner :)

Wallpanel is worth looking at for it's full-screen capabilities! I'm going to close this issue as it covers the requested functionality.

**Comment by mikeage** [comment]
Thanks, I'll check out wallpanel too!
