### ISSUE TITLE
Home vs not home

### ISSUE THREAD

**Issue by shadowdro** [malcolmrigg/WizardClock#9]
I have a person that doesn't have a phone with space to add apps, so I just want her to do as home or traveling. I use the router to see if she is here, and that part works. It shows her device as not_home, however, on the card it only shows her as home. Is it looking for an attribute? This device only has 2 states, home or not_home. The only attributes are name and source. I don't understand why is not working.

**Comment by malcolmrigg** [comment]
Hi, have you set the "lost" value in configuration? You need to set that to tell the clock what to display when an entity returns "not_home".

E.g:
locations:
  - Home
  - Work
  - School
lost: Travelling
type: 'custom:weasley-card'
wizards:
... etc

Let me know if that fixes it :)

**Comment by shadowdro** [comment]
Actually that did. Thanks a bunch! I didn't know they were connected.

**Comment by malcolmrigg** [comment]
Great 👍 

Looking at it, it might make more sense to use "not_home" instead of "lost" as the config item, to make it a bit more obvious. I'll add that to my todo list.
